name: init
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    if: github.repository != 'kaskadi/template-npm-pkg'
    steps:
    - uses: actions/checkout@v2
    - name: Import GPG key for kaskadi-bot
      uses: crazy-max/ghaction-import-gpg@v2
      with:
        git_user_signingkey: true
        git_commit_gpgsign: true
      env:
        GPG_PRIVATE_KEY: ${{ secrets.KASKADI_BOT_GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.KASKADI_BOT_GPG_PRIVATE_PASSPHRASE }}
    - name: Initialize repository
      uses: kaskadi/action-init@master
      with:
        repoType: 'package'
      env:
        CC_TOKEN: ${{ secrets.CC_TOKEN }}
        GH_ACCESS_TOKEN: ${{ secrets.GH_REPO_ACCESS_TOKEN }}
